devmode = false

[postgresql]
  enabled = false
  url = ""
  password = ""

[log]
  file = ""

[srv]
  host = "0.0.0.0"
  port = 8080
  # IPs exempt from ratelimiting.
  ratelimit_exempt = [
    "192.168.0.0/16",
  ]
  api_version = "1.0.0"

[pages]
  frontend_version = "1.0.0"